import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AuthProvider from '@/context/AuthProvider';
import { Toaster } from '@/components/ui/toaster';
import ApolloProviderWrapper from '@/context/ApolloProvider';
import ReactQueryProviderWrapper from '@/context/QueryProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <ReactQueryProviderWrapper>
      <ApolloProviderWrapper>
        <AuthProvider>
          <body className={inter.className}>
            {children}
            <Toaster />
          </body>
        </AuthProvider>
      </ApolloProviderWrapper>
      </ReactQueryProviderWrapper>
    </html>
  );
}
